import Icon from "./Icon";
import DropDownArrow from "./DropDownArrow";
import Search from "./Search";
import Calendar from "./Calendar";
import ViewSimple from "./ViewSimple";
import Bin from "./Bin";
import DashBoard from "./Dashboard";
import Chart from "./Chart";
import Toggle from "./Toggle";
import Paper from "./Paper";
import Graph from "./Graph";
import Chatroom from "./Chatroom";
import Repeat from "./Repeat";
import Setting from "./Setting";
import Home from "./Home";
import Profile from "./Profile";
import Download from "./Download";
import Message from "./Message";
import NotificationBell from "./NotificationBell";
import Attachment from "./Attachment";
import RingBell from "./RingBell";
import Dot from "./Dot";
import Line from "./Line";
import Right from "./Right";
import Left from "./Left";
import Logo from "./Logo";
import Edit from "./Edit";
import Link from "./Link";
import TrashCan from "./TrashCan";
import PdfType from "./PdfType";
import ZipType from "./ZipType";
import DocType from "./DocType";
import UnknownFile from "./UnknownFile";
import PngType from "./PngType";
import GifType from "./GifType";
import TaskIcon from "./TaskIcon";
import JpgType from "./JpgType";
import SvgType from "./SvgType";
import TxtType from "./TxtType";
import FileIcon from "./FileIcon";
import Camera from './Camera';


Icon.Search = Search;
Icon.DropDownArrow = DropDownArrow;
Icon.Calendar = Calendar;
Icon.ViewSimple = ViewSimple;
Icon.Bin = Bin;
Icon.DashBoard = DashBoard;
Icon.Chart = Chart;
Icon.Toggle = Toggle;
Icon.Paper = Paper;
Icon.Graph = Graph;
Icon.Chatroom = Chatroom;
Icon.Repeat = Repeat;
Icon.Setting = Setting;
Icon.Home = Home;
Icon.Profile = Profile;
Icon.Download = Download;
Icon.Message = Message;
Icon.NotificationBell = NotificationBell;
Icon.Attachment = Attachment;
Icon.RingBell = RingBell;
Icon.Dot = Dot;
Icon.Line = Line;
Icon.Right = Right;
Icon.Left = Left;
Icon.Logo = Logo;
Icon.Edit = Edit;
Icon.Link = Link;
Icon.TrashCan = TrashCan;
Icon.PdfType = PdfType;
Icon.ZipType = ZipType;
Icon.DocType = DocType;
Icon.UnknownFile = UnknownFile;
Icon.PngType = PngType;
Icon.GifType = GifType;
Icon.TaskIcon = TaskIcon;
Icon.JpgType = JpgType;
Icon.SvgType =SvgType;
Icon.TxtType = TxtType;
Icon.FileIcon = FileIcon;
Icon.Camera = Camera;

export { Icon };
